"""Add trading_signals table

Revision ID: 15c805118f10
Revises: 89337a4e9d2b
Create Date: 2025-12-04 01:46:08.153360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15c805118f10'
down_revision: Union[str, None] = '89337a4e9d2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create trading_signals table
    op.create_table(
        'trading_signals',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('strategy_id', sa.Integer(), nullable=True),
        sa.Column('symbol', sa.String(length=20), nullable=False),
        sa.Column('signal_type', sa.String(length=10), nullable=False),
        sa.Column('timeframe', sa.String(length=10), nullable=False),
        sa.Column('price', sa.Float(), nullable=True),
        sa.Column('indicators', sa.JSON(), nullable=True),
        sa.Column('confidence', sa.Float(), nullable=True),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trading_signals_id'), 'trading_signals', ['id'], unique=False)
    op.create_index(op.f('ix_trading_signals_timestamp'), 'trading_signals', ['timestamp'], unique=False)
    op.create_index('idx_signal_user_timestamp', 'trading_signals', ['user_id', 'timestamp'], unique=False)
    op.create_index('idx_signal_symbol', 'trading_signals', ['symbol'], unique=False)
    op.create_index('idx_signal_strategy', 'trading_signals', ['strategy_id'], unique=False)

    # SQLite doesn't support ALTER COLUMN, skip these changes
    # op.alter_column('users', 'role',
    #            existing_type=sa.VARCHAR(),
    #            nullable=False)
    # op.alter_column('users', 'exchange',
    #            existing_type=sa.VARCHAR(),
    #            nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop trading_signals table
    op.drop_index('idx_signal_strategy', table_name='trading_signals')
    op.drop_index('idx_signal_symbol', table_name='trading_signals')
    op.drop_index('idx_signal_user_timestamp', table_name='trading_signals')
    op.drop_index(op.f('ix_trading_signals_timestamp'), table_name='trading_signals')
    op.drop_index(op.f('ix_trading_signals_id'), table_name='trading_signals')
    op.drop_table('trading_signals')

    # SQLite doesn't support ALTER COLUMN
    # op.alter_column('users', 'exchange',
    #            existing_type=sa.VARCHAR(),
    #            nullable=True)
    # op.alter_column('users', 'role',
    #            existing_type=sa.VARCHAR(),
    #            nullable=True)
    # ### end Alembic commands ###
