"""add exchange field to user

Revision ID: ad9472a74882
Revises: 001
Create Date: 2025-12-01 20:38:38.620702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad9472a74882'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite doesn't support ALTER COLUMN, so we add with default value and server_default
    op.add_column('users', sa.Column('exchange', sa.String(), nullable=False, server_default='bitget'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'exchange')
    # ### end Alembic commands ###
