#!/bin/bash
# ============================================================
# Production Deployment Script
# 서버 배포 자동화 - 환경변수 검증 포함
# ============================================================

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

# Configuration - Seoul Server (Vultr)
# Hetzner 서버 (5.161.112.248)는 2026-01-12에 완전 삭제됨
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
SERVER_IP="141.164.55.245"
SERVER_USER="root"
SERVER_PATH="/root/group_c"

# Production URLs
PRODUCTION_API_URL="https://api.deepsignal.shop"
PRODUCTION_FRONTEND_URL="https://deepsignal.shop"

ssh_cmd() {
    ssh -i ~/.ssh/hetzner_deploy_key -o StrictHostKeyChecking=no ${SERVER_USER}@${SERVER_IP} "$@"
}

print_header() {
    echo -e "\n${CYAN}╔════════════════════════════════════════════════════════════╗${NC}"
    printf "${CYAN}║  %-58s ║${NC}\n" "$1"
    echo -e "${CYAN}╚════════════════════════════════════════════════════════════╝${NC}"
}

print_step() {
    echo -e "\n${BLUE}▶ $1${NC}"
}

print_success() {
    echo -e "${GREEN}✅ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

print_error() {
    echo -e "${RED}❌ $1${NC}"
}

# ============================================================
# Step 1: Pre-deployment Checks
# ============================================================
pre_deploy_checks() {
    print_header "Step 1: Pre-deployment Validation"

    cd "$PROJECT_DIR"

    # 1.1 Ensure frontend .env.production has correct URL
    print_step "Checking frontend/.env.production..."
    if [ -f "frontend/.env.production" ]; then
        local current=$(grep "^VITE_API_URL=" frontend/.env.production 2>/dev/null | cut -d'=' -f2)
        if [ "$current" != "$PRODUCTION_API_URL" ]; then
            print_warning "Fixing frontend/.env.production"
            cat > frontend/.env.production << EOF
# Production Environment Variables
# Auto-generated by deploy-production.sh
VITE_API_URL=${PRODUCTION_API_URL}
EOF
        fi
        print_success "frontend/.env.production → $PRODUCTION_API_URL"
    fi

    # 1.2 Ensure admin-frontend .env.production has correct URL
    print_step "Checking admin-frontend/.env.production..."
    if [ -d "admin-frontend" ]; then
        cat > admin-frontend/.env.production << EOF
# Production Environment Variables
# Auto-generated by deploy-production.sh
VITE_API_URL=${PRODUCTION_API_URL}
EOF
        print_success "admin-frontend/.env.production → $PRODUCTION_API_URL"
    fi

    # 1.3 Check server .env has VITE_API_URL
    print_step "Checking server .env..."
    local server_vite_url=$(ssh_cmd "grep '^VITE_API_URL=' ${SERVER_PATH}/.env 2>/dev/null | cut -d'=' -f2" || echo "")

    if [ -z "$server_vite_url" ]; then
        print_warning "Adding VITE_API_URL to server .env"
        ssh_cmd "echo 'VITE_API_URL=${PRODUCTION_API_URL}' >> ${SERVER_PATH}/.env"
        print_success "Added VITE_API_URL to server .env"
    elif [ "$server_vite_url" != "$PRODUCTION_API_URL" ]; then
        print_warning "Updating VITE_API_URL in server .env"
        ssh_cmd "sed -i 's|^VITE_API_URL=.*|VITE_API_URL=${PRODUCTION_API_URL}|' ${SERVER_PATH}/.env"
        print_success "Updated VITE_API_URL in server .env"
    else
        print_success "Server VITE_API_URL is correct"
    fi

    # 1.4 Check CORS_ORIGINS
    print_step "Checking CORS_ORIGINS..."
    local cors=$(ssh_cmd "grep '^CORS_ORIGINS=' ${SERVER_PATH}/.env 2>/dev/null | cut -d'=' -f2" || echo "")
    if [[ ! "$cors" =~ "deepsignal.shop" ]]; then
        print_warning "Updating CORS_ORIGINS to include deepsignal.shop"
        local new_cors="https://deepsignal.shop,https://admin.deepsignal.shop,http://141.164.55.245:3201,http://141.164.55.245:3202"
        ssh_cmd "grep -q '^CORS_ORIGINS=' ${SERVER_PATH}/.env && sed -i 's|^CORS_ORIGINS=.*|CORS_ORIGINS=${new_cors}|' ${SERVER_PATH}/.env || echo 'CORS_ORIGINS=${new_cors}' >> ${SERVER_PATH}/.env"
    fi
    print_success "CORS_ORIGINS configured"
}

# ============================================================
# Step 2: Build Frontend Locally
# ============================================================
build_frontend() {
    print_header "Step 2: Building Frontend"

    cd "$PROJECT_DIR/frontend"

    print_step "Installing dependencies..."
    npm ci --silent 2>/dev/null || npm install --silent

    print_step "Building with production environment..."
    npm run build

    # Verify build
    print_step "Verifying build..."
    if grep -q "api.ai-deepsignal" dist/assets/index-*.js 2>/dev/null; then
        print_success "Build verified: contains correct API URL"
    elif grep -q "localhost:8000" dist/assets/index-*.js 2>/dev/null; then
        print_error "Build contains localhost:8000!"
        print_error "Check VITE_API_URL in frontend/.env.production"
        exit 1
    else
        print_warning "Could not verify API URL in build (may be minified)"
    fi
}

# ============================================================
# Step 3: Sync Files to Server
# ============================================================
sync_files() {
    print_header "Step 3: Syncing Files to Server"

    cd "$PROJECT_DIR"

    print_step "Syncing project files..."
    rsync -avz --delete \
        --exclude 'node_modules' \
        --exclude '.git' \
        --exclude '__pycache__' \
        --exclude '*.pyc' \
        --exclude '.env' \
        --exclude 'trading.db' \
        --exclude 'logs/*' \
        --exclude '.scannerwork' \
        --exclude 'bitget-futures-trading' \
        --exclude 'futures_trading_agent' \
        -e "ssh -i ~/.ssh/hetzner_deploy_key -o StrictHostKeyChecking=no" \
        ./ ${SERVER_USER}@${SERVER_IP}:${SERVER_PATH}/

    print_success "Files synced to server"
}

# ============================================================
# Step 4: Rebuild Docker Containers
# ============================================================
rebuild_containers() {
    print_header "Step 4: Rebuilding Docker Containers"

    print_step "Rebuilding frontend container (no cache)..."
    ssh_cmd "cd ${SERVER_PATH} && docker compose build --no-cache frontend"

    if [ -d "$PROJECT_DIR/admin-frontend" ]; then
        print_step "Rebuilding admin-frontend container (no cache)..."
        ssh_cmd "cd ${SERVER_PATH} && docker compose build --no-cache admin-frontend" || true
    fi

    print_step "Restarting containers..."
    ssh_cmd "cd ${SERVER_PATH} && docker compose up -d frontend"

    if [ -d "$PROJECT_DIR/admin-frontend" ]; then
        ssh_cmd "cd ${SERVER_PATH} && docker compose up -d admin-frontend" || true
    fi

    print_success "Containers rebuilt and restarted"
}

# ============================================================
# Step 5: Post-deployment Verification
# ============================================================
verify_deployment() {
    print_header "Step 5: Post-deployment Verification"

    print_step "Waiting for services to start..."
    sleep 10

    # Check container status
    print_step "Container status:"
    ssh_cmd "docker ps --format 'table {{.Names}}\t{{.Status}}' | grep trading"

    # Verify frontend API URL in container
    print_step "Verifying frontend configuration..."
    local in_container=$(ssh_cmd "docker exec trading-frontend grep -o 'api.ai-deepsignal' /usr/share/nginx/html/assets/index-*.js 2>/dev/null | head -1" || echo "")

    if [ -n "$in_container" ]; then
        print_success "Frontend using: api.deepsignal.shop"
    else
        local has_localhost=$(ssh_cmd "docker exec trading-frontend grep -o 'localhost:8000' /usr/share/nginx/html/assets/index-*.js 2>/dev/null | head -1" || echo "")
        if [ -n "$has_localhost" ]; then
            print_error "Frontend still using localhost:8000!"
            print_error "Container may be using cached image."
            print_error "Try: docker compose build --no-cache frontend"
            exit 1
        fi
        print_warning "Could not verify API URL (may be minified)"
    fi

    # Test endpoints
    print_step "Testing endpoints..."

    local frontend_status=$(curl -s -o /dev/null -w "%{http_code}" $PRODUCTION_FRONTEND_URL 2>/dev/null || echo "000")
    if [ "$frontend_status" == "200" ]; then
        print_success "Frontend: $PRODUCTION_FRONTEND_URL (HTTP $frontend_status)"
    else
        print_warning "Frontend: HTTP $frontend_status"
    fi

    local api_status=$(curl -s -o /dev/null -w "%{http_code}" $PRODUCTION_API_URL/health 2>/dev/null || echo "000")
    if [ "$api_status" == "200" ]; then
        print_success "API: $PRODUCTION_API_URL (HTTP $api_status)"
    else
        print_warning "API: HTTP $api_status"
    fi

    # Test login API
    print_step "Testing login API..."
    local login_response=$(curl -s -X POST "$PRODUCTION_API_URL/api/v1/auth/login" \
        -H "Content-Type: application/json" \
        -d '{"email":"admin@admin.com","password":"Admin123!"}' 2>/dev/null || echo "{}")

    if echo "$login_response" | grep -q "access_token"; then
        print_success "Login API working correctly"
    else
        print_warning "Login API may have issues"
        echo "$login_response" | head -c 200
    fi
}

# ============================================================
# Main
# ============================================================
main() {
    print_header "🚀 Production Deployment"
    echo -e "Server: ${SERVER_USER}@${SERVER_IP}"
    echo -e "Target: ${SERVER_PATH}"
    echo -e "Time: $(date)"

    pre_deploy_checks
    build_frontend
    sync_files
    rebuild_containers
    verify_deployment

    print_header "✅ Deployment Complete!"
    echo ""
    echo -e "${GREEN}Frontend: ${PRODUCTION_FRONTEND_URL}${NC}"
    echo -e "${GREEN}API: ${PRODUCTION_API_URL}${NC}"
    echo ""
    echo -e "${YELLOW}Tip: Clear browser cache (Ctrl+Shift+R) to see changes${NC}"
}

# Handle arguments
case "${1:-}" in
    --check)
        pre_deploy_checks
        ;;
    --build)
        build_frontend
        ;;
    --sync)
        sync_files
        ;;
    --rebuild)
        rebuild_containers
        verify_deployment
        ;;
    --verify)
        verify_deployment
        ;;
    --help|-h)
        echo "Usage: $0 [option]"
        echo ""
        echo "Options:"
        echo "  (no args)   Full deployment"
        echo "  --check     Pre-deployment checks only"
        echo "  --build     Build frontend only"
        echo "  --sync      Sync files to server only"
        echo "  --rebuild   Rebuild containers only"
        echo "  --verify    Post-deployment verification only"
        echo "  --help      Show this help"
        ;;
    *)
        main
        ;;
esac
